categories:
  - labels:
      - "feat"
    title: "New Features"
  - labels:
      - "fix"
    title: "Bug Fixes"
  - labels:
      - "update"
    title: Updates
  - labels:
      - "chore"
      - "build"
      - "refactor"
      - "test"
    title: Chores
  - labels:
      - security
      - "security"
    title: "Security Related"

include-labels:
  - "feat"
  - "fix"
  - "update"
  - "chore"
  - "build"
  - "refactor"
  - "test"
  - "security"
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |
  ## Changes

  $CHANGES
